name: jiffy
description: Jiffy is a date dart package inspired by momentjs for parsing, manipulating and formatting dates
version: 5.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.18.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.5
  coverage: ^1.0.2
